FROM eclipse-temurin:17-jdk AS cache

COPY . /app
WORKDIR /app

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY

RUN apt update -y && apt upgrade -y

RUN ./gradlew assemble -x test -x asciidoctor && \
    rm -rf /app
