---
spring.config.activate.on-profile: sandbox

open-search:
  indices:
    test: sandbox-logstash-logs

---
spring.config.activate.on-profile: stable

open-search:
  indices:
    test: stable-logstash-logs
