spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 8 # DB 최대 세션수가 30개인데 서버배포시 rolling update를 할때 디폴트 값인 10개씩 먹으면 아슬아슬해서 줄였습니다!
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100 # 나중에 부족하시면 늘려주세요!
    hibernate:
      ddl-auto: validate
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
logging:
  level:
    org:
      hibernate: info

---
spring:
  config.activate.on-profile: sandbox
  datasource:
    hikari:
      maximum-pool-size: 4 # 샌박은 동시에 DB에 붙을 서버가 많아서 더 작게 설정했습니다
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# 요 아래 설정들은 테스트 작성하실때 사용할 메모리 DB 연결 설정입니다!
spring:
  config.activate.on-profile: test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: off
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

logging:
  level:
    org:
      hibernate: trace
