[[Auth-API]]
= *Auth API*

[[애플-로그인-API]]
== *1. 애플 로그인 API*

=== *1-1 성공*

operation::auth-controller-test/apple-login-success[snippets='http-request,request-body,request-fields,http-response']

=== *1-2 실패 - 유효하지만 서버에 가입되지 않은 파이어베이스 아이디 토큰이면*

operation::auth-controller-test/apple-login-fail-not-registered-token[snippets='http-request,request-body,request-fields,http-response']

=== *1-3 실패 - 유효하지 않은 파이어베이스 아이디 토큰이면*

operation::auth-controller-test/apple-login-fail-invalid-token[snippets='http-request,request-body,request-fields,http-response']

[[카카오-로그인-API]]
== *2. 카카오 로그인 API*

=== *2-1 성공*

operation::auth-controller-test/kakao-login-success[snippets='http-request,request-body,request-fields,http-response,response-fields']

=== *2-2 실패 - 유효하지만 서버에 가입되지 않은 파이어베이스 아이디 토큰이면*

operation::auth-controller-test/kakao-login-fail-not-registered-token[snippets='http-request,request-body,request-fields,http-response,response-fields']

=== *2-3 실패 - 카카오 회원 정보 요청 중, 예외가 발생하면*

operation::auth-controller-test/kakao-login-fail-webclient-error[snippets='http-request,request-body,request-fields,http-response']

=== *2-3 실패 - 커스텀 토큰 생성에 실패하면*

operation::auth-controller-test/kakao-login-fail-create-token-error[snippets='http-request,request-body,request-fields,http-response']

[[애플-회원가입-API]]
== *3. 애플-회원가입 API*

=== *3-1 성공*

operation::auth-controller-test/apple-register-success[snippets='http-request,request-body,request-fields,http-response']

=== *3-2 실패 - FIREBASE에 등록되지 않은 ID TOKEN이 주어지면*

operation::auth-controller-test/apple-register-fail-not-register-token[snippets='http-request,request-body,request-fields,http-response']

=== *3-3 실패 - 유효한 토큰이지만, 이미 존재하는 사용자면*

operation::auth-controller-test/apple-register-fail-exist-user[snippets='http-request,request-body,request-fields,http-response']

=== *3-4 실패 - 유효한 토큰이지만, 이미 존재하는 이메일이면*

operation::auth-controller-test/apple-register-fail-exist-email[snippets='http-request,request-body,request-fields,http-response']

=== *3-5 실패 - 유효한 토큰이지만, 이미 존재하는 전화번호이면*

operation::auth-controller-test/apple-register-fail-exist-phone-number[snippets='http-request,request-body,request-fields,http-response']

=== *3-6 실패 - 유효한 토큰이지만, 이미 존재하는 닉네임이면*

operation::auth-controller-test/apple-register-fail-exist-nickname[snippets='http-request,request-body,request-fields,http-response']

=== *3-7 실패 - 유효한 토큰이지만, 유효하지 않은 형식의 이메일이면*

operation::auth-controller-test/apple-register-fail-invalid-email[snippets='http-request,request-body,request-fields,http-response']

=== *3-8 실패 - 유효한 토큰이지만, 유효하지 않은 형식의 전화번호이면*

operation::auth-controller-test/apple-register-fail-invalid-phone-number[snippets='http-request,request-body,request-fields,http-response']

[[카카오-회원가입-API]]
== *4. 카카오-회원가입 API*

=== *4-1 성공*

operation::auth-controller-test/kakao-register-success[snippets='http-request,request-body,request-fields,http-response']

=== *4-2 실패 - FIREBASE에 이미 존재하는 USERNAME이 전달되면*

operation::auth-controller-test/kakao-register-fail-exist-username-in-firebase[snippets='http-request,request-body,request-fields,http-response']

=== *4-3 실패 - 유효한 토큰이지만, 이미 존재하는 사용자면*

operation::auth-controller-test/kakao-register-fail-exist-user[snippets='http-request,request-body,request-fields,http-response']

=== *4-4 실패 - 유효한 토큰이지만, 이미 존재하는 이메일이면*

operation::auth-controller-test/kakao-register-fail-exist-email[snippets='http-request,request-body,request-fields,http-response']

=== *4-5 실패 - 유효한 토큰이지만, 이미 존재하는 전화번호이면*

operation::auth-controller-test/kakao-register-fail-exist-phone-number[snippets='http-request,request-body,request-fields,http-response']

=== *4-6 실패 - 유효한 토큰이지만, 이미 존재하는 닉네임이면*

operation::auth-controller-test/kakao-register-fail-exist-nickname[snippets='http-request,request-body,request-fields,http-response']

=== *4-7 실패 - 유효한 토큰이지만, 유효하지 않은 형식의 이메일이면*

operation::auth-controller-test/kakao-register-fail-invalid-email[snippets='http-request,request-body,request-fields,http-response']

=== *4-8 실패 - 유효한 토큰이지만, 유효하지 않은 형식의 전화번호이면*

operation::auth-controller-test/kakao-register-fail-invalid-phone-number[snippets='http-request,request-body,request-fields,http-response']

=== *4-9 실패 - 유효한 토큰이지만, 필수 약관이 모두 포함되지 않은 리스트가 전달되면*

operation::auth-controller-test/kakao-register-fail-not-found-required-terms[snippets='http-request,request-body,request-fields,http-response']

=== *4-10 실패 - 유효한 토큰이지만, 존재하지 않는 약관 ID가 리스트 포함되어 있으면*

operation::auth-controller-test/kakao-register-fail-not-found-terms[snippets='http-request,request-body,request-fields,http-response']

=== *4-11 실패 - 유효한 토큰이지만, 빈 약관 ID 리스트이면*

operation::auth-controller-test/kakao-register-fail-empty-terms-id-list[snippets='http-request,request-body,request-fields,http-response']

[[닉네임-중복-검사-API]]
== *5. 닉네임 중복 검사 API*

=== *5-1 성공*

operation::auth-controller-test/validate-nickname-success[snippets='http-request,query-parameters,http-response']

=== *5-2 실패 - 중복인 닉네임*

operation::auth-controller-test/validate-nickname-fail-exist-nickname[snippets='http-request,query-parameters,http-response']

[[이메일-중복-검사-API]]
== *6. 이메일 중복 검사 API*

=== *6-1 성공*

operation::auth-controller-test/validate-email-success[snippets='http-request,query-parameters,http-response']

=== *6-2 실패 - 중복인 이메일*

operation::auth-controller-test/validate-email-fail-exist-nickname[snippets='http-request,query-parameters,http-response']

[[전화번호-중복-검사-API]]
== *7. 전화번호 중복 검사 API*

=== *7-1 성공*

operation::auth-controller-test/validate-phone-number-success[snippets='http-request,query-parameters,http-response']

=== *7-2 실패 - 중복인 전화번호*

operation::auth-controller-test/validate-phone-number-fail-exist-nickname[snippets='http-request,query-parameters,http-response']

[[약관리스트조회API]]
== *8. 약관 리스트 조회 API*

=== *8-1 성공*

operation::auth-controller-test/terms-list-success[snippets='http-request,http-response']

[[약관내용조회API]]
== *9. 약관 내용 조회 API*

=== *9-1 성공*

operation::auth-controller-test/terms-get-success[snippets='http-request,path-parameters,http-response']

=== *9-2 실패 - 양수가 아닌 약관 ID*

operation::auth-controller-test/terms-get-fail-invalid-id[snippets='http-request,path-parameters,http-response']

=== *9-3 실패 - 존재하지 않는 약관 ID*

operation::auth-controller-test/terms-get-fail-not-exist-id[snippets='http-request,path-parameters,http-response']
