[[Auth-API]]
= *Auth API*

[[로그인-API]]
== *1. 로그인 API*

=== *1-1 성공*

operation::auth-controller-test/login-success[snippets='http-request,request-body,request-fields,http-response']

=== *1-2 실패 - 유효하지만 가입되지 않은 토큰*

operation::auth-controller-test/login-fail-not-registered-token[snippets='http-request,request-body,request-fields,http-response,response-fields']

=== *1-3 실패 - 유효하지 않은 토큰*

operation::auth-controller-test/login-fail-invalid-token[snippets='http-request,request-body,request-fields,http-response,response-fields']

[[회원가입-API]]
== *2. 회원가입 API*

=== *2-1 성공*

operation::auth-controller-test/register-success[snippets='http-request,path-parameters,request-body,request-fields,http-response']

=== *2-2 실패 - 유효한 토큰이지만, 이미 존재하는 사용자*

operation::auth-controller-test/register-fail-exist-user[snippets='http-request,path-parameters,request-body,request-fields,http-response,response-fields']

=== *2-3 실패 - 유효한 토큰이지만, 이미 존재하는 닉네임*

operation::auth-controller-test/register-fail-exist-nickname[snippets='http-request,path-parameters,request-body,request-fields,http-response,response-fields']

=== *2-4 실패 - 유효한 토큰이지만, 유효하지 않은 형식의 이메일*

operation::auth-controller-test/register-fail-invalid-email[snippets='http-request,path-parameters,request-body,request-fields,http-response,response-fields']

=== *2-5 실패 - 유효한 토큰이지만, 유효하지 않은 형식의 전화번호*

operation::auth-controller-test/register-fail-invalid-phone-number[snippets='http-request,path-parameters,request-body,request-fields,http-response,response-fields']

=== *2-5 실패 - 유효하지 않은 토큰*

operation::auth-controller-test/register-fail-invalid-token[snippets='http-request,path-parameters,request-body,request-fields,http-response,response-fields']

[[닉네임-중복-검사-API]]
== *3. 닉네임 중복 검사 API*

=== *3-1 성공*

operation::auth-controller-test/validate-nickname-success[snippets='http-request,query-parameters,http-response']

=== *3-2 실패 - 중복인 닉네임*

operation::auth-controller-test/validate-nickname-success[snippets='http-request,query-parameters,http-response']
