[[PlaceReview-API]]
= *PlaceReview API*

[[장소리뷰생성-API]]
== *1. 장소 리뷰 생성 API*

=== *1-1 성공*

operation::place-review-controller-test/placeReview-create-success[snippets='http-request,request-headers,request-body,request-fields,http-response']

=== *1-2 실패 - 유효한 토큰이지만 최소보다 미만인 별점*

operation::place-review-controller-test/placeReview-create-fail-too-low-rating[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *1-3 실패 - 유효한 토큰이지만 최대보다 초과인 별점*

operation::place-review-controller-test/placeReview-create-fail-too-high-rating[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *1-4 실패 - 유효한 토큰이지만 공백인 리뷰*

operation::place-review-controller-test/placeReview-create-fail-blank-review[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *1-5 실패 - 유효한 토큰이지만 최대 길이를 초과한 리뷰*

operation::place-review-controller-test/placeReview-create-fail-too-long-review[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *1-6 실패 - 가입되지 않은 유저*

operation::place-review-controller-test/placeReview-create-fail-not-registered-user[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *1-7 실패 - 유효한 토큰이지만 이미 리뷰한 장소를 리뷰*

operation::place-review-controller-test/placeReview-create-fail-already-written-review[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *1-8 실패 - 유효하지 않은 토큰*

operation::place-review-controller-test/placeReview-create-fail-invalid-token[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

[[장소리뷰수정-API]]
== *2. 장소 리뷰 수정 API*

=== *2-1 성공*

operation::place-review-controller-test/placeReview-update-success[snippets='http-request,request-headers,request-body,request-fields,http-response']

=== *2-2 실패 - 유효한 토큰이지만 음수인 장소리뷰ID*

operation::place-review-controller-test/placeReview-update-fail-negative-rating[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *2-3 실패 - 유효한 토큰이지만 최소보다 미만인 별점*

operation::place-review-controller-test/placeReview-update-fail-too-low-rating[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *2-4 실패 - 유효한 토큰이지만 최대보다 초과인 별점*

operation::place-review-controller-test/placeReview-update-fail-too-high-rating[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *2-5 실패 - 유효한 토큰이지만, 최소 길이 미만인 리뷰*

operation::place-review-controller-test/placeReview-update-fail-too-short-review[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *2-6 실패 - 유효한 토큰이지만 최대 길이를 초과한 리뷰*

operation::place-review-controller-test/placeReview-update-fail-too-long-review[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *2-7 실패 - 가입되지 않은 유저*

operation::place-review-controller-test/placeReview-update-fail-not-registered-user[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *2-8 실패 - 유효한 토큰이지만 존재하지 않는 장소리뷰ID*

operation::place-review-controller-test/placeReview-update-fail-not-found-review[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *2-9 실패 - 유효한 토큰이지만 수정할 권한의 유저*

operation::place-review-controller-test/placeReview-update-fail-no-permissions[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

=== *2-10 실패 - 유효하지 않은 토큰*

operation::place-review-controller-test/placeReview-update-fail-invalid-token[snippets='http-request,request-headers,request-body,request-fields,response-body,http-response']

[[장소리뷰삭제-API]]
== *3. 장소 리뷰 삭제 API*

=== *3-1 성공*

operation::place-review-controller-test/placeReview-delete-success[snippets='http-request,path-Parameters,request-Headers,http-response']

=== *3-2 실패 - 유효한 토큰이지만 음수인 장소리뷰ID*

operation::place-review-controller-test/placeReview-delete-fail-negative-id[snippets='http-request,path-Parameters,request-headers,response-body,http-response']

=== *3-3 실패 - 가입되지 않은 유저*

operation::place-review-controller-test/placeReview-delete-fail-not-registered-user[snippets='http-request,path-Parameters,request-headers,response-body,http-response']

=== *3-4 실패 - 유효한 토큰이지만 존재하지 않는 장소리뷰ID인 경우*

operation::place-review-controller-test/placeReview-delete-not-found-id[snippets='http-request,path-Parameters,request-headers,response-body,http-response']

=== *3-5 실패 - 유효한 토큰이지만, 삭제할 권한이 없는 경우*

operation::place-review-controller-test/placeReview-delete-no-permissions[snippets='http-request,path-Parameters,request-headers,response-body,http-response']

=== *3-6 실패 - 유효하지 않은 토큰*

operation::place-review-controller-test/placeReview-delete-invalid-token[snippets='http-request,path-Parameters,request-headers,response-body,http-response']

[[장소ID리뷰조회-API]]
== *4. 장소 ID 리뷰 조회 API*

=== *4-1 성공*

operation::place-review-controller-test/placeReview-placeId-get-list-success[snippets='http-request,path-Parameters,request-Headers,query-parameters,response-body,http-response']

=== *4-2 실패 - 가입되지 않은 유저*

operation::place-review-controller-test/placeReview-placeId-get-fail-not-registered-user[snippets='http-request,path-Parameters,request-Headers,query-parameters,response-body,http-response']

=== *4-3 실패 - 유효하지 않은 토큰*

operation::place-review-controller-test/placeReview-placeId-get-fail-invalid-token[snippets='http-request,path-Parameters,request-headers,query-parameters,response-body,http-response']

[[유저ID리뷰조회-API]]
== *5. 유저 ID 리뷰 조회 API*

=== *5-1 성공*

operation::place-review-controller-test/placeReview-userId-get-list-success[snippets='http-request,path-Parameters,request-Headers,query-parameters,response-body,http-response']

=== *5-2 실패 - 유효한 토큰이지만 음수인 유저 ID*

operation::place-review-controller-test/placeReview-userId-get-fail-negative-id[snippets='http-request,path-Parameters,request-Headers,query-parameters,response-body,http-response']

=== *5-3 실패 - 가입되지 않은 유저*

operation::place-review-controller-test/placeReview-userId-get-fail-not-registered-user[snippets='http-request,path-Parameters,request-Headers,query-parameters,response-body,http-response']

=== *5-4 실패 - 유효한 토큰이지만 가입되어 있지 않은 USER ID로 조회*

operation::place-review-controller-test/placeReview-userId-get-fail-lookup-not-registered-id[snippets='http-request,path-Parameters,request-headers,query-parameters,response-body,http-response']

=== *5-5 실패 - 유효하지 않은 토큰*

operation::place-review-controller-test/placeReview-userId-get-fail-invalid-token[snippets='http-request,path-Parameters,request-headers,query-parameters,response-body,http-response']
