[[PlaceReview-API]]
= *PlaceReview API*

[[장소리뷰생성-API]]
== *1. 장소 리뷰 생성 API*

=== *1-1 성공*

operation::place-review-controller-test/placeReview-create-success[snippets='http-request,request-body,request-fields,http-response']

=== *1-2 실패 - 유효한 토큰이지만 최소보다 미만인 별점*

operation::place-review-controller-test/placeReview-create-fail-too-low-rating[snippets='http-request,request-body,request-fields,http-response']

=== *1-3 실패 - 유효한 토큰이지만 최대보다 초과인 별점*

operation::place-review-controller-test/placeReview-create-fail-too-high-rating[snippets='http-request,request-body,request-fields,http-response']

=== *1-4 실패 - 유효한 토큰이지만 공백인 리뷰*

operation::place-review-controller-test/placeReview-create-fail-blank-review[snippets='http-request,request-body,request-fields,http-response']

=== *1-5 실패 - 유효한 토큰이지만 최대 길이를 초과한 리뷰*

operation::place-review-controller-test/placeReview-create-fail-too-long-review[snippets='http-request,request-body,request-fields,http-response']

=== *1-6 실패 - 가입되지 않은 유저*

operation::place-review-controller-test/placeReview-create-fail-not-registered-user[snippets='http-request,request-body,request-fields,http-response']

=== *1-7 실패 - 유효한 토큰이지만 이미 리뷰한 장소를 리뷰*

operation::place-review-controller-test/placeReview-create-fail-already-written-review[snippets='http-request,request-body,request-fields,http-response']

=== *1-8 실패 - 유효하지 않은 토큰*

operation::place-review-controller-test/placeReview-create-fail-invalid-token[snippets='http-request,request-body,request-fields,http-response,response-fields']

[[장소리뷰수정-API]]
== *2. 장소 리뷰 수정 API*

=== *2-1 성공*

operation::place-review-controller-test/placeReview-update-success[snippets='http-request,request-body,request-fields,http-response']

=== *2-2 실패 - 유효한 토큰이지만 음수인 장소리뷰ID*

operation::place-review-controller-test/placeReview-update-fail-negative-rating[snippets='http-request,request-body,request-fields,http-response']

=== *2-3 실패 - 유효한 토큰이지만 최소보다 미만인 별점*

operation::place-review-controller-test/placeReview-update-fail-too-low-rating[snippets='http-request,request-body,request-fields,http-response']

=== *2-4 실패 - 유효한 토큰이지만 최대보다 초과인 별점*

operation::place-review-controller-test/placeReview-update-fail-too-high-rating[snippets='http-request,request-body,request-fields,http-response']

=== *2-5 실패 - 유효한 토큰이지만, 최소 길이 미만인 리뷰*

operation::place-review-controller-test/placeReview-update-fail-too-short-review[snippets='http-request,request-body,request-fields,http-response']

=== *2-6 실패 - 유효한 토큰이지만 최대 길이를 초과한 리뷰*

operation::place-review-controller-test/placeReview-update-fail-too-long-review[snippets='http-request,request-body,request-fields,http-response']

=== *2-7 실패 - 가입되지 않은 유저*

operation::place-review-controller-test/placeReview-update-fail-not-registered-user[snippets='http-request,request-body,request-fields,http-response']

=== *2-8 실패 - 유효한 토큰이지만 존재하지 않는 장소리뷰ID*

operation::place-review-controller-test/placeReview-update-fail-not-found-review[snippets='http-request,request-body,request-fields,http-response']

=== *2-9 실패 - 유효한 토큰이지만 수정할 권한의 유저*

operation::place-review-controller-test/placeReview-update-fail-no-permissions[snippets='http-request,request-body,request-fields,http-response,response-fields']

=== *2-10 실패 - 유효하지 않은 토큰*

operation::place-review-controller-test/placeReview-update-fail-invalid-token[snippets='http-request,request-body,request-fields,http-response,response-fields']
