[[Report-API]]
= *Report API*

== *ReportReason*

|===
| status | value

| `SPAM`
| 스팸 및 홍보글

| `PORNOGRAPHY`
| 음란성이 포함된 글

| `SWEAR_WORD`
| 욕설/생명경시/혐오/차별적인 글

| `OVER_POST`
| 게시글 도배

| `INFO_LEAK`
| 개인정보 노출 및 불법 정보

| `OTHER`
| 기타
|===

[[신고사유리스트출력-API]]
== *1. 신고 사유 리스트 출력 API*

=== *1-1 성공*

operation::report-controller-test/report-reasons-get-success[snippets='http-request,request-headers,response-fields,http-response']

=== *1-2 실패 - 유효하지 않은 토큰*

operation::report-controller-test/report-reasons-get-fail-invalid-token[snippets='http-request,request-headers,http-response']

[[한줄리뷰신고API]]
== *2. 한줄리뷰 신고 API*

=== *1-1 성공 - 등록된 사유*

operation::report-controller-test/report-place-review-success[snippets='http-request,request-headers,request-fields,http-response']

=== *1-2 성공 - 기타 사유*

operation::report-controller-test/report-place-review-other-reason-success[snippets='http-request,request-headers,request-fields,http-response']

=== *1-3 실패 - 양수가 아닌 한 줄 리뷰 ID*

operation::report-controller-test/report-place-review-fail-invalid-place-review-id[snippets='http-request,request-headers,request-fields,http-response']

=== *1-4 실패 - 공백인 기타 사유*

operation::report-controller-test/report-place-review-fail-empty-other-reason[snippets='http-request,request-headers,request-fields,http-response']

=== *1-5 실패 - 최대 길이를 초과한 기타 사유(20자)*

operation::report-controller-test/report-place-review-fail-too-long-other-reason[snippets='http-request,request-headers,request-fields,http-response']

=== *1-6 실패 - 존재하지 않는 한 줄 리뷰 ID*

operation::report-controller-test/report-place-review-fail-not-exist-place-review-id[snippets='http-request,request-headers,request-fields,http-response']

=== *1-7 실패 - 자신의 한 줄 리뷰 신고*

operation::report-controller-test/report-place-review-fail-can-not-report-own-post[snippets='http-request,request-headers,request-fields,http-response']

=== *1-8 실패 - 이미 신고한 한 줄 리뷰 ID*

operation::report-controller-test/report-place-review-fail-already-report-post[snippets='http-request,request-headers,request-fields,http-response']

=== *1-9 실패 - 유효하지 않은 토큰*

operation::report-controller-test/report-place-review-fail-invalid-token[snippets='http-request,request-headers,http-response']

[[여행일지신고API]]
== *3. 여행 일지 신고 API*

=== *1-1 성공 - 등록된 사유*

operation::report-controller-test/report-travel-journal-success[snippets='http-request,request-headers,request-fields,http-response']

=== *1-2 성공 - 기타 사유*

operation::report-controller-test/report-travel-journal-other-reason-success[snippets='http-request,request-headers,request-fields,http-response']

=== *1-3 실패 - 양수가 아닌 여행 일지 ID*

operation::report-controller-test/report-travel-journal-fail-invalid-travel-journal-id[snippets='http-request,request-headers,request-fields,http-response']

=== *1-4 실패 - 공백인 기타 사유*

operation::report-controller-test/report-travel-journal-fail-empty-other-reason[snippets='http-request,request-headers,request-fields,http-response']

=== *1-5 실패 - 최대 길이를 초과한 기타 사유(20자)*

operation::report-controller-test/report-travel-journal-fail-too-long-other-reason[snippets='http-request,request-headers,request-fields,http-response']

=== *1-6 실패 - 존재하지 않는 여행 일지 ID*

operation::report-controller-test/report-travel-journal-fail-not-exist-travel-journal-id[snippets='http-request,request-headers,request-fields,http-response']

=== *1-7 실패 - 자신의 여행 일지 신고*

operation::report-controller-test/report-travel-journal-fail-can-not-report-own-post[snippets='http-request,request-headers,request-fields,http-response']

=== *1-8 실패 - 이미 신고한 여행 일지 ID*

operation::report-controller-test/report-travel-journal-fail-already-report-post[snippets='http-request,request-headers,request-fields,http-response']

=== *1-9 실패 - 유효하지 않은 토큰*

operation::report-controller-test/report-travel-journal-fail-invalid-token[snippets='http-request,request-headers,http-response']
