[[TravelJournal-API]]
= *TravelJournal API*

== *Visibility*

|===
| status | value

| `PUBLIC`
| 모두 공개

| `FRIEND_ONLY`
| 친구에게만 공개

| `PRIVATE`
| 비공개

|===

== *TravelJournalSortType*

|===
| status | value

| `LATEST`
| 최신순
|===

[[여행일지생성-API]]
== *1. 여행 일지 생성 API*

=== *1-1 성공*

operation::travel-journal-controller-test/travel-journals-success[snippets='http-request,request-headers,request-parts,http-response']

=== *1-2 성공 - nullable 필드들이 전부 null*

operation::travel-journal-controller-test/travel-journals-nullable-success[snippets='http-request,request-headers,request-parts,http-response']

=== *1-3 실패 - 제목이 20자가 넘는 경우*

operation::travel-journal-controller-test/travel-journals-failure-title[snippets='http-request,request-headers,request-parts,http-response']

=== *1-4 실패 - 여행 일지 콘텐츠가 15개 초과인 경우*

operation::travel-journal-controller-test/travel-journals-failure-content-size[snippets='http-request,request-headers,request-parts,http-response']

=== *1-5 실패 - 여행 일지 콘텐츠의 이미지 제목이 비어있는 경우*

operation::travel-journal-controller-test/travel-journals-failure-image-name-empty[snippets='http-request,request-headers,request-parts,http-response']

=== *1-6 실패 - 여행 일지 콘텐츠의 이미지 제목 개수가 15개를 초과하는 경우*

operation::travel-journal-controller-test/travel-journals-failure-image-name-size[snippets='http-request,request-headers,request-parts,http-response']

=== *1-7 실패 - 여행 이미지가 비어있는 경우*

operation::travel-journal-controller-test/travel-journals-fail-image-size-empty[snippets='http-request,request-headers,request-parts,http-response']

=== *1-8 실패 - 여행 이미지가 225개를 초과하는 경우*

operation::travel-journal-controller-test/travel-journals-fail-image-size-over-225[snippets='http-request,request-headers,request-parts,http-response']

=== *1-9 실패 - 여행 일지의 시작일이 여행 일지의 종료일보다 늦을 경우*

operation::travel-journal-controller-test/travel-journals-fail-travel-start-date-after-travel-end-date[snippets='http-request,request-headers,request-parts,http-response']

=== *1-10 실패 - 여행 일지 콘텐츠의 이미지 이름 개수와 실제 이미지 개수가 다를 경우*

operation::travel-journal-controller-test/travel-journals-fail-image-name-size-not-equal-to-image-size[snippets='http-request,request-headers,request-parts,http-response']

=== *1-11 실패 - 여행 일자보다 콘텐츠의 개수가 많을 경우*

operation::travel-journal-controller-test/travel-journals-fail-travel-journal-content-size-more-than-travel-date-size[snippets='http-request,request-headers,request-parts,http-response']

=== *1-12 실패 - 여행 콘텐츠 일자가 여행 시작일보다 이전이거나 여행 종료일보다 이후일 경우*

operation::travel-journal-controller-test/travel-journals-fail-travel-journal-content-travel-date-not-in-travel-date-range[snippets='http-request,request-headers,request-parts,http-response']

=== *1-13 실패 - 여행 일자가 15일 초과인 경우*

operation::travel-journal-controller-test/travel-journals-fail-travel-end-date-over-15-days[snippets='http-request,request-headers,request-parts']

=== *1-14 실패 - 여행 친구 아이디가 등록되지 않은 사용자인 경우*

operation::travel-journal-controller-test/travel-journals-fail-travel-friend-not-found[snippets='http-request,request-headers,request-parts,http-response']

=== *1-15 실패 - 여행 친구가 10명 초과인 경우*

operation::travel-journal-controller-test/travel-journals-fail-travel-friend-over-10[snippets='http-request,request-headers,request-parts,http-response']

=== *1-16 실패 - 여행 일지 콘텐츠의 이름이 실제 이미지 파일 이름과 일치하지 않는 경우*

operation::travel-journal-controller-test/travel-journals-fail-travel-journal-content-image-name-not-equal-to-image-name[snippets='http-request,request-headers,request-parts,http-response']

=== *1-17 실패 - 위도와 경도 중에 하나만 null인 경우*

operation::travel-journal-controller-test/travel-journals-fail-latitude-longitude-only-one-null[snippets='http-request,request-headers,request-parts,http-response']

=== *1-18 실패 - 위도와 경도의 개수가 다를 경우*

operation::travel-journal-controller-test/travel-journals-fail-latitude-longitude-size-not-equal[snippets='http-request,request-headers,request-parts,http-response']

=== *1-19 실패 - 유효하지 않은 장소 id인 경우*

operation::travel-journal-controller-test/travel-journals-fail-invalid-place-id[snippets='http-request,request-headers,request-parts,http-response']

=== *1-20 실패 - 여행 일지 콘텐츠 이미지 저장에 실패하는 경우*

operation::travel-journal-controller-test/travel-journals-fail-travel-journal-content-image-upload-fail[snippets='http-request,request-headers,request-parts,http-response']

=== *1-21 실패 - 여행 일지를 등록하려는 사용자가 없는 경우*

operation::travel-journal-controller-test/travel-journals-fail-user-not-found[snippets='http-request,request-headers,request-parts,http-response']

=== *1-22 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/travel-journals-fail-invalid-token[snippets='http-request,request-headers,request-parts,http-response']

[[여행일지조회-API]]
== *2. 여행 일지 조회 API*

=== *2-1 성공*

operation::travel-journal-controller-test/get-travel-journal-success[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

=== *2-2 실패 - 비공개 여행 일지이지만, 작성자가 요청하지 않은 경우*

operation::travel-journal-controller-test/get-travel-journal-fail-not-writer[snippets='http-request,request-headers,path-parameters,http-response']

=== *2-3 실패 - 친구 공개 여행 일지이지만, 친구가 아닌 사용자가 요청한 경우"*

operation::travel-journal-controller-test/get-travel-journal-fail-not-friend[snippets='http-request,request-headers,path-parameters,http-response']

=== *2-4 실패 - 유효하지 않은 토큰일 경우"*

operation::travel-journal-controller-test/get-travel-journal-fail-invalid-token[snippets='http-request,request-headers,path-parameters,http-response']

[[여행일지목록조회-API]]
== *3. 여행 일지 목록 조회 API*

=== *3-1 성공*

operation::travel-journal-controller-test/get-travel-journals-success[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== *3-2 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/get-travel-journals-fail-invalid-token[snippets='http-request,request-headers,query-parameters,http-response']

[[나의여행일지목록조회-API]]
== *4. 나의 여행 일지 목록 조회 API*

=== *4-1 성공*

operation::travel-journal-controller-test/get-my-travel-journals-success[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== *4-2 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/get-my-travel-journals-fail-invalid-token[snippets='http-request,request-headers,query-parameters,http-response']

[[친구여행일지목록조회-API]]
== *5. 친구 여행 일지 목록 조회 API*

=== *5-1 성공*

operation::travel-journal-controller-test/get-friend-travel-journals-success[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== *5-2 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/get-friend-travel-journals-fail-invalid-token[snippets='http-request,request-headers,query-parameters,http-response']

[[추천여행일지목록조회-API]]
== *6. 추천 여행 일지 목록 조회 API*

=== *6-1 성공*

operation::travel-journal-controller-test/get-recommend-travel-journals-success[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== *6-2 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/get-recommend-travel-journals-fail-invalid-token[snippets='http-request,request-headers,query-parameters,http-response']

[[태그된-여행-일지-조회-API]]
== *7. 태그된 여행 일지 목록 조회 API*

=== *7-1 성공*

operation::travel-journal-controller-test/get-tagged-travel-journals-success[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

=== *7-2 실패 - 유효하지 않은 마지막 id일 경우*

operation::travel-journal-controller-test/get-tagged-travel-journals-fail-invalid-last-id[snippets='http-request,request-headers,query-parameters,http-response']

=== *7-3 실패 - 유효하지 않은 사이즈*

operation::travel-journal-controller-test/get-tagged-travel-journals-fail-invalid-size[snippets='http-request,request-headers,query-parameters,http-response']

=== *7-4 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/get-tagged-travel-journals-fail-invalid-token[snippets='http-request,request-headers,query-parameters,http-response']


[[여행일지수정-API]]
== *8. 여행 일지 수정 API*

=== *8-1 성공*

operation::travel-journal-controller-test/travel-journals-update-success[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *8-2 실패 - 작성자가 아닌 사용자가 요청한 경우*

operation::travel-journal-controller-test/travel-journals-update-fail-not-same-user[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *8-3 실패 - 여행 시작일이 여행 종료일보다 늦는 경우*

operation::travel-journal-controller-test/travel-journals-update-fail-later-start-date[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *8-4 실패 - 여행 기간이 제한 기간보다 긴 경우*

operation::travel-journal-controller-test/travel-journals-update-fail-longer-than-max-days[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *8-5 실패 - 여행 일지 기간과 여행 일지 콘텐츠 개수가 다른 경우*

operation::travel-journal-controller-test/travel-journals-update-fail-not-same-content-count[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *8-6 실패 - 여행 일지 콘텐츠의 날짜와 여행 시작일, 종료일 사이에 없는 경우*

operation::travel-journal-controller-test/travel-journals-update-fail-content-date-not-between-start-end-date[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *8-7 실패 - 여행 친구 수가 제한 친구 수보다 많은 경우*

operation::travel-journal-controller-test/travel-journals-update-fail-over-max-companion-count[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *8-8 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/travel-journals-update-fail-invalid-token[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

[[여행일지콘텐츠수정-API]]
== *9. 여행 일지 콘텐츠 수정 API*

=== *9-1 성공*

operation::travel-journal-controller-test/travel-journal-contents-update-success[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *9-2 실패 - 여행 일지 콘텐츠 아이디에 맞는 여행 일지 콘텐츠가 없는 경우*

operation::travel-journal-controller-test/travel-journal-content-update-fail-not-found-content[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *9-3 실패 - 작성자와 요청자가 다른 경우*

operation::travel-journal-controller-test/travel-journal-content-update-fail-not-same-user[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *9-4 실패 - 여행 일지 콘텐츠의 이미지 개수가 제한 개수보다 많은 경우*

operation::travel-journal-controller-test/travel-journal-content-update-fail-over-max-image-count[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *9-5 실패 - 추가할 여행 일지 콘텐츠의 이름과 이미지 파일의 이름이 다른 경우*

operation::travel-journal-controller-test/travel-journal-content-update-fail-not-same-image-name[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *9-6 실패 - 여행 일지 콘텐츠 여행 일자가 여행 시작일과 종료일 사이에 없는 경우*

operation::travel-journal-controller-test/travel-journal-content-update-fail-travel-date-not-between-start-date-and-end-date[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *9-7 실패 - 위도와 경도의 개수가 다른 경우*

operation::travel-journal-controller-test/travel-journal-content-update-fail-not-same-size-of-latitudes-and-longitudes[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

=== *9-8 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/travel-journal-content-update-fail-invalid-token[snippets='http-request,request-headers,path-parameters,request-parts,http-response']

[[여행일지삭제-API]]
== *10. 여행 일지 삭제 API*

=== *10-1 성공*

operation::travel-journal-controller-test/travel-journals-delete-success[snippets='http-request,request-headers,path-parameters,http-response']

=== *10-2 실패 - 작성자와 요청자가 다른 경우*

operation::travel-journal-controller-test/travel-journals-delete-fail-not-same-user[snippets='http-request,request-headers,path-parameters,http-response']

=== *10-3 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/travel-journals-delete-fail-invalid-token[snippets='http-request,request-headers,path-parameters,http-response']

[[여행일지콘텐츠삭제-API]]
== *11. 여행 일지 콘텐츠 삭제 API*

=== *11-1 성공*

operation::travel-journal-controller-test/travel-journal-content-delete-success[snippets='http-request,request-headers,path-parameters,http-response']

=== *11-2 실패 - 작성자와 요청자가 다른 경우*

operation::travel-journal-controller-test/travel-journal-content-delete-fail-not-same-user[snippets='http-request,request-headers,path-parameters,http-response']

=== *11-3 실패 - 여행 일지 콘텐츠 아이디와 일치하는 여행 일지 콘텐츠가 없는 경우*

operation::travel-journal-controller-test/travel-journal-content-delete-fail-not-found[snippets='http-request,request-headers,path-parameters,http-response']

=== *11-4 실패 - 유효하지 않은 토큰일 경우*

operation::travel-journal-controller-test/travel-journal-content-delete-fail-invalid-token[snippets='http-request,request-headers,path-parameters,http-response']
