[[User-API]]
= *User API*

[[사용자-정보-조회-API]]
== *1. 사용자 정보 조회(me) API*

=== *1-1 성공*

operation::user-controller-test/get-my-information-success[snippets='http-request,request-headers,http-response,response-fields']

=== *1-2 실패 - 유효한 토큰이면서, 가입되지 않은 사용자*

operation::user-controller-test/get-my-information-fail-not-registered-user[snippets='http-request,request-headers,http-response']

=== *1-3 실패 - 유효한 토큰이면서, 프로필 PreAuthentication Access Url 생성에 실패한 경우*

operation::user-controller-test/get-my-information-fail-create-pre-authentication-access-url[snippets='http-request,request-headers,http-response']

=== *1-4 실패 - 유효하지 않은 토큰*

operation::user-controller-test/get-my-information-fail-invalid-token[snippets='http-request,request-headers,http-response']

[[이메일-변경-API]]
== *2. 이메일 변경 API*

=== *2-1 성공*

operation::user-controller-test/update-email-success[snippets='http-request,request-headers,http-response']

=== *2-2 실패 - 유효한 토큰이면서, 인증된 이메일이 토큰에 없는 경우*

operation::user-controller-test/update-email-fail-not-exist-email-in-token[snippets='http-request,request-headers,http-response']

=== *2-3 실패 - 유효한 토큰이면서, 가입되어 있는 이메일인 경우*

operation::user-controller-test/update-email-fail-exist-email[snippets='http-request,request-headers,http-response']

=== *2-4 실패 - 유효하지 않은 토큰*

operation::user-controller-test/update-email-fail-invalid-token[snippets='http-request,request-headers,http-response']

[[전화번호-변경-API]]
== *3. 전화번호 변경 API*

=== *3-1 성공*

operation::user-controller-test/update-phone-number-success[snippets='http-request,request-headers,http-response']

=== *3-2 실패 - 유효한 토큰이면서, 인증된 전화번호가 토큰에 없는 경우*

operation::user-controller-test/update-phone-number-fail-not-exist-phone-number-in-token[snippets='http-request,request-headers,http-response']

=== *3-3 실패 - 유효한 토큰이면서, 가입되어 있는 전화번호인 경우*

operation::user-controller-test/update-phone-number-fail-exist-email[snippets='http-request,request-headers,http-response']

=== *3-4 실패 - 유효하지 않은 토큰*

operation::user-controller-test/update-phone-number-fail-invalid-token[snippets='http-request,request-headers,http-response']

[[정보-변경-API]]
== *4. 정보 변경 API*

=== *4-1 성공*

operation::user-controller-test/update-information-success[snippets='http-request,request-headers,request-fields,http-response']

=== *4-2 실패 - 유효한 토큰이면서, 중복된 닉네임인 경우*

operation::user-controller-test/update-information-fail-exist-nickname[snippets='http-request,request-headers,request-fields,http-response']

=== *4-3 실패 - 유효하지 않은 토큰*

operation::user-controller-test/update-information-fail-invalid-token[snippets='http-request,request-headers,http-response']

[[프로필-변경-API]]
== *5. 프로필 변경 API*

=== *5-1 성공 프로필 사진을 전송한 경우*

operation::user-controller-test/update-profile-image-success[snippets='http-request,request-headers,request-parts,http-response']

=== *5-2 성공 프로필 사진을 전송하지 않은 경우 (기본 프로필로 변경)*

operation::user-controller-test/update-profile-image-success-without-profile-image[snippets='http-request,request-headers,http-response']

=== *5-3 실패 - 유효한 토큰이면서, 프로필 사진의 형식이 잘못된 경우*

operation::user-controller-test/update-profile-image-fail-invalid-format[snippets='http-request,request-headers,request-parts,http-response']

=== *5-4 실패 - 유효한 토큰이면서, 프로필 사진의 원본 파일 이름이 존재하지 않는 경우*

operation::user-controller-test/update-profile-image-fail-not-exist-origin-file-name[snippets='http-request,request-headers,request-parts,http-response']

=== *5-5 실패 - 유효한 토큰이면서, Object Storage에 저장하는데 실패한 경우*

operation::user-controller-test/update-profile-image-fail-object-storage-error[snippets='http-request,request-headers,request-parts,http-response']

=== *5-6 실패 - 유효한 토큰이면서, 프로필 사진을 첨부하지 않고 이미 기본 프로필인 경우*

operation::user-controller-test/update-profile-image-fail-invalid-delete-default-profile[snippets='http-request,request-headers,http-response']

=== *5-7 실패 - 유효한 토큰이면서, Object Storage에 프로필이 없어 삭제에 실패한 경우*

operation::user-controller-test/update-profile-image-fail-delete-not-exist-profile[snippets='http-request,request-headers,http-response']

=== *5-8 실패 - 유효한 토큰이면서, 프로필 삭제에 실패한 경우*

operation::user-controller-test/update-profile-image-fail-delete-profile-error[snippets='http-request,request-headers,http-response']

=== *5-9 실패 - 유효한 토큰이면서, DB에 프로필 색상이 없는 경우*

operation::user-controller-test/update-profile-image-fail-object-storage-error[snippets='http-request,request-headers,request-parts,http-response']

=== *5-10 실패 - 유효하지 않은 토큰이면*

operation::user-controller-test/update-profile-image-fail-unauthorized[snippets='http-request,request-headers,request-parts,http-response']

[[FCM-token-변경-API]]
== *6. FCM token 변경 API*

=== *6-1 성공*

operation::user-controller-test/update-fcm-token-success[snippets='http-request,request-headers,request-fields,http-response']

=== *6-2 실패 - 유효하지 않은 FcmToken*

operation::user-controller-test/update-fcm-token-failed-invalid-fcm-token[snippets='http-request,request-headers,request-fields,http-response']

=== *6-3 실패 - 유효하지 않은 토큰*

operation::user-controller-test/update-fcm-token-fail-invalid-token[snippets='http-request,request-headers,request-fields,http-response']


[[회원탈퇴-API]]
== *7. 회원 탈퇴 API*

=== *7-1 성공*

operation::user-controller-test/withdraw-user-success[snippets='http-request,request-headers,http-response']

=== *7-2 실패 - 유효하지 않은 토큰*

operation::user-controller-test/withdraw-user-fail-unauthorized[snippets='http-request,request-headers,http-response']

[[유저-검색-API]]
== *8. 유저 검색 API*

=== *8-1 성공*

operation::user-controller-test/search-users-success[snippets='http-request,query-parameters,request-headers,http-response']

=== *8-2 실패 - 유효하지 않은 닉네임*

operation::user-controller-test/search-users-fail-nickname-blank[snippets='http-request,query-parameters,request-headers,http-response']

=== *8-3 실패 - 유효하지 않은 마지막 id*

operation::user-controller-test/search-users-fail-invalid-last-id[snippets='http-request,query-parameters,request-headers,http-response']

=== *8-4 실패 - 유효하지 않은 사이즈*

operation::user-controller-test/search-users-fail-invalid-size[snippets='http-request,query-parameters,request-headers,http-response']

=== *8-5 실패 - 가입되지 않은 유저*

operation::user-controller-test/search-users-fail-not-registered-user[snippets='http-request,request-headers,http-response']

=== *8-6 실패 - 유효하지 않은 토큰*

operation::user-controller-test/search-users-fail-invalid-token[snippets='http-request,request-headers,http-response']

[[유저-통계-API]]
== *9. 유저 통계 API*

=== *9-1 성공*

operation::user-controller-test/get-user-statistics-success[snippets='http-request,request-headers,path-parameters,http-response']

=== *9-2 실패 - USER ID가 음수인 경우*

operation::user-controller-test/get-user-statistics-fail-user-id-negative[snippets='http-request,request-headers,path-parameters,http-response']

=== *9-3 실패 - 가입되지 않은 사용자인 경우*

operation::user-controller-test/get-user-statistics-fail-not-registered-user[snippets='http-request,request-headers,path-parameters,http-response']

=== *9-4 실패 - 유효하지 않은 토큰인 경우*

operation::user-controller-test/get-user-statistics-fail-invalid-token[snippets='http-request,request-headers,path-parameters,http-response']


[[유저-인생샷-API]]
== *10. 유저 인생샷 API*

=== *10-1 성공*

operation::user-controller-test/get-life-shots-success[snippets='http-request,query-parameters,path-parameters,request-headers,http-response']

=== *10-2 실패 - 유효하지 않은 user id*

operation::user-controller-test/get-life-shots-fail-invalid-user-id[snippets='http-request,query-parameters,path-parameters,request-headers,http-response']

=== *10-3 실패 - 유효하지 않은 마지막 id*

operation::user-controller-test/get-life-shots-fail-invalid-last-id[snippets='http-request,query-parameters,path-parameters,request-headers,http-response']

=== *10-4 실패 - 유효하지 않은 사이즈*

operation::user-controller-test/get-life-shots-fail-invalid-size[snippets='http-request,query-parameters,path-parameters,request-headers,http-response']

=== *10-5 실패 - 가입되지 않은 유저*

operation::user-controller-test/get-life-shots-fail-not-registered-user[snippets='http-request,request-headers,http-response']

=== *10-6 실패 - 유효하지 않은 토큰*

operation::user-controller-test/get-life-shots-fail-invalid-token[snippets='http-request,request-headers,http-response']
