ALTER TABLE PLACE_REVIEW
    MODIFY "COMMENT" VARCHAR2(90);

ALTER TABLE PLACE_REVIEW
    RENAME COLUMN "COMMENT" TO review;

ALTER TABLE PLACE_REVIEW
    DROP PRIMARY KEY DROP INDEX;

CREATE SEQUENCE PLACE_REVIEW_SEQ INCREMENT BY 1 START WITH 1;

ALTER TABLE PLACE_REVIEW
    ADD ID NUMERIC(19, 0) NOT NULL;

ALTER TABLE place_review
    ADD CONSTRAINT primary_place_review PRIMARY KEY (ID);

ALTER TABLE place_review
    ADD CONSTRAINT place_id_user_id_unique UNIQUE (PLACE_ID, USER_ID);
